export {
  EmulationClientError,
  type EmulationClientErrorDetails,
} from './emulation_client_error.ts';
export type { EmulationSessionClient } from './emulation_session_client.ts';
export {
  TelegramEmulationClient,
  type TelegramEmulationClientOptions,
} from './telegram_emulation_client.ts';
export type {
  AccountBotCommandsInput,
  AccountEditMessageInput,
  AccountMessageHistoryInput,
  AccountReplyInterfaceInput,
  AccountSendMessageInput,
  AddChatMemberInput,
  BotBlockInput,
  BotCommand,
  CallbackInlineKeyboardButton,
  CallbackQuery,
  CallbackQueryAnswer,
  CallbackQueryStatus,
  CreatedVirtualAccount,
  CreatedVirtualBot,
  CreateSupergroupInput,
  CreateVirtualAccountInput,
  CreateVirtualBotInput,
  EmulationSession,
  ForceReplyInterface,
  InlineKeyboardButton,
  InlineKeyboardMarkup,
  MessageEntity,
  MessageSenderBot,
  MessageTarget,
  PlainMessageEntityType,
  PressCallbackButtonInput,
  PressReplyKeyboardButtonInput,
  PrivateChat,
  PrivateMessageTarget,
  PrivateTextMessage,
  RepliedPrivateTextMessage,
  RepliedSupergroupTextMessage,
  ReplyInterface,
  ReplyKeyboardButton,
  ReplyKeyboardInterface,
  Supergroup,
  SupergroupChat,
  SupergroupMessageTarget,
  SupergroupTextMessage,
  TextMessageIn,
  UrlInlineKeyboardButton,
  VirtualAccountClient,
  VirtualAccountProfile,
  VirtualBotProfile,
} from './types.ts';
