export {
  EmulationClientError,
  type EmulationClientErrorDetails,
} from './emulation_client_error.ts';
export type { EmulationSessionClient } from './emulation_session_client.ts';
export {
  TelegramEmulationClient,
  type TelegramEmulationClientOptions,
} from './telegram_emulation_client.ts';
export type {
  AccountBotCommandsInput,
  AccountEditMessageCaptionInput,
  AccountEditMessageInput,
  AccountMessageHistoryInput,
  AccountReplyInterfaceInput,
  AccountSendDocumentInput,
  AccountSendMessageInput,
  AccountSendPhotoInput,
  AddChatMemberInput,
  BotBlockInput,
  BotCommand,
  CallbackInlineKeyboardButton,
  CallbackQuery,
  CallbackQueryAnswer,
  CallbackQueryStatus,
  CreatedVirtualAccount,
  CreatedVirtualBot,
  CreateSupergroupInput,
  CreateVirtualAccountInput,
  CreateVirtualBotInput,
  Document,
  EmulationSession,
  ForceReplyInterface,
  InlineKeyboardButton,
  InlineKeyboardMarkup,
  MessageContent,
  MessageEntity,
  MessageIn,
  MessageSenderBot,
  MessageTarget,
  PhotoSize,
  PlainMessageEntityType,
  PressCallbackButtonInput,
  PressReplyKeyboardButtonInput,
  PrivateChat,
  PrivateMessage,
  PrivateMessageTarget,
  RepliedPrivateMessage,
  RepliedSupergroupMessage,
  ReplyInterface,
  ReplyKeyboardButton,
  ReplyKeyboardInterface,
  Supergroup,
  SupergroupChat,
  SupergroupMessage,
  SupergroupMessageTarget,
  UrlInlineKeyboardButton,
  VirtualAccountClient,
  VirtualAccountProfile,
  VirtualBotProfile,
} from './types.ts';
